# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='MATRIZ', max_length=15)),
                ('razao_social', models.CharField(max_length=60)),
                ('nome_fantasia', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
                ('data_processamento', models.DateField(max_length=8)),
                ('data_competencia', models.DateField(max_length=8)),
                ('site_empresa', models.CharField(max_length=100)),
                ('email_empresa', models.CharField(max_length=100)),
                ('cnpj', models.BigIntegerField(unique=True)),
                ('inscricao_estadual', models.CharField(max_length=15)),
                ('inscricao_municipal', models.CharField(max_length=15)),
                ('tipo_empresa', models.CharField(max_length=2)),
                ('agrupa_itens_pedido', models.CharField(default='N', max_length=1)),
                ('bloqueia_clientes_em_atraso', models.CharField(default='N', max_length=1)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
    ]
